2022-12-05 17:48:28,061 INFO    MainThread:9136 [wandb_setup.py:_flush():68] Configure stats pid to 9136
2022-12-05 17:48:28,061 INFO    MainThread:9136 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Calculos\.config\wandb\settings
2022-12-05 17:48:28,061 INFO    MainThread:9136 [wandb_setup.py:_flush():68] Loading settings from d:\UniSergio\BasketScripts\WaB\wandb\settings
2022-12-05 17:48:28,061 INFO    MainThread:9136 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-05 17:48:28,061 INFO    MainThread:9136 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-05 17:48:28,061 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,062 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,062 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,062 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,062 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,062 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,063 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,063 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,063 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,063 ERROR   MainThread:9136 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-05 17:48:28,063 INFO    MainThread:9136 [wandb_init.py:_log_setup():476] Logging user logs to d:\UniSergio\BasketScripts\WaB\wandb\run-20221205_174828-2v7jmskh\logs\debug.log
2022-12-05 17:48:28,063 INFO    MainThread:9136 [wandb_init.py:_log_setup():477] Logging internal logs to d:\UniSergio\BasketScripts\WaB\wandb\run-20221205_174828-2v7jmskh\logs\debug-internal.log
2022-12-05 17:48:28,064 INFO    MainThread:9136 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001B88C0B9340>
2022-12-05 17:48:28,064 INFO    MainThread:9136 [wandb_init.py:init():516] calling init triggers
2022-12-05 17:48:28,064 INFO    MainThread:9136 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'num_neurons': 100, 'acti_fun': 'relu', 'batch_size': 150, 'epochs': 500, 'architecture': 'OneHiddenLayer', 'dataset': '2020-21_traditional', 'loss': 0.35824069380760193, 'acc': 0.7546666860580444, 'val_loss': 0.6650004386901855, 'val_acc': 0.6380000114440918}
2022-12-05 17:48:28,064 INFO    MainThread:9136 [wandb_init.py:init():569] starting backend
2022-12-05 17:48:28,064 INFO    MainThread:9136 [wandb_init.py:init():573] setting up manager
2022-12-05 17:48:28,065 INFO    MainThread:9136 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-12-05 17:48:28,067 INFO    MainThread:9136 [wandb_init.py:init():580] backend started and connected
2022-12-05 17:48:28,068 INFO    MainThread:9136 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2022-12-05 17:48:28,068 INFO    MainThread:9136 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-12-05 17:48:28,068 INFO    MainThread:9136 [wandb_init.py:init():658] updated telemetry
2022-12-05 17:48:28,068 INFO    MainThread:9136 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-05 17:48:29,461 INFO    MainThread:9136 [wandb_run.py:_on_init():2000] communicating current version
2022-12-05 17:48:29,591 INFO    MainThread:9136 [wandb_run.py:_on_init():2004] got version response 
2022-12-05 17:48:29,591 INFO    MainThread:9136 [wandb_init.py:init():728] starting run threads in backend
2022-12-05 17:48:32,157 INFO    MainThread:9136 [wandb_run.py:_console_start():1980] atexit reg
2022-12-05 17:48:32,158 INFO    MainThread:9136 [wandb_run.py:_redirect():1838] redirect: SettingsConsole.WRAP_RAW
2022-12-05 17:48:32,158 INFO    MainThread:9136 [wandb_run.py:_redirect():1903] Wrapping output streams.
2022-12-05 17:48:32,158 INFO    MainThread:9136 [wandb_run.py:_redirect():1925] Redirects installed.
2022-12-05 17:48:32,158 INFO    MainThread:9136 [wandb_init.py:init():765] run started, returning control to user process
2022-12-05 17:48:32,417 INFO    MainThread:9136 [wandb_run.py:_finish():1746] finishing run progettobasket/TTra2021runs/2v7jmskh
2022-12-05 17:48:32,418 ERROR   MainThread:9136 [jupyter.py:save_history():440] Run pip install nbformat to save notebook history
2022-12-05 17:48:32,418 INFO    MainThread:9136 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2022-12-05 17:48:32,418 INFO    MainThread:9136 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2022-12-05 17:48:32,418 INFO    MainThread:9136 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-12-05 17:48:32,418 INFO    MainThread:9136 [wandb_run.py:_restore():1932] restore
2022-12-05 17:48:32,419 INFO    MainThread:9136 [wandb_run.py:_restore():1938] restore done
2022-12-05 17:48:36,212 INFO    MainThread:9136 [wandb_run.py:_footer_history_summary_info():3377] rendering history
2022-12-05 17:48:36,213 INFO    MainThread:9136 [wandb_run.py:_footer_history_summary_info():3409] rendering summary
2022-12-05 17:48:36,217 INFO    MainThread:9136 [wandb_run.py:_footer_sync_info():3333] logging synced files
